/**
 * WebViewEditor — TipTap editor running inside a WebView.
 * Provides rich text editing (bold, italic, underline, strikethrough,
 * bullet lists, checklists) with the same TipTap engine as the webapp.
 */
import React, { useEffect, useRef, useCallback, useState } from 'react';
import { View, StyleSheet, Platform } from 'react-native';
import { WebView } from 'react-native-webview';
import type { WebViewMessageEvent } from 'react-native-webview';
import { useEditorBridge } from '@toonnotes/editor-web/hooks';
import type { EditorBridgeAPI } from '@toonnotes/editor-web/hooks';
import { textToHtml } from '@toonnotes/editor-core';
// The HTML bundle is generated by `pnpm --filter @toonnotes/editor-web build`
// and exported as a string constant from the /html subpath.
// For development, we use a fallback inline HTML.
let EDITOR_HTML: string;
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  EDITOR_HTML = require('@toonnotes/editor-web/html').EDITOR_HTML;
} catch {
  // Fallback: minimal HTML that loads nothing (build the editor-web package first)
  EDITOR_HTML = `
    <!DOCTYPE html>
    <html><head><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" /></head>
    <body><div id="editor" contenteditable="true" style="min-height:300px;font-size:17px;outline:none;padding:0;">
    <p style="color:#9CA3AF;">Build @toonnotes/editor-web first</p>
    </div></body></html>
  `;
}

export interface WebViewEditorProps {
  /** Initial content as plain text (will be converted to HTML via textToHtml) */
  initialContent: string;
  /** Background color for the editor */
  backgroundColor: string;
  /** Text color for the editor */
  textColor: string;
  /** Accent color (checkboxes, links) */
  accentColor: string;
  /** Whether dark mode is active */
  isDark: boolean;
  /** Optional font family */
  fontFamily?: string;
  /** Called on every content change */
  onContentChange: (plainText: string, html: string, cursorOffset: number) => void;
  /** Called when editor is ready */
  onEditorReady?: () => void;
  /** Called when editor focus changes */
  onFocusChange?: (focused: boolean) => void;
  /** Expose bridge API to parent for toolbar integration */
  bridgeRef?: React.MutableRefObject<EditorBridgeAPI | null>;
}

export function WebViewEditor({
  initialContent,
  backgroundColor,
  textColor,
  accentColor,
  isDark,
  fontFamily,
  onContentChange,
  onEditorReady,
  onFocusChange,
  bridgeRef,
}: WebViewEditorProps) {
  const [webViewHeight, setWebViewHeight] = useState(300);
  const hasSetInitialContent = useRef(false);

  const bridge = useEditorBridge({
    onContentChange,
    onEditorReady: useCallback(() => {
      // Set initial content once editor is ready
      if (!hasSetInitialContent.current) {
        hasSetInitialContent.current = true;
        const html = textToHtml(initialContent);
        bridge.setContent(html);

        // Apply initial theme
        bridge.setTheme({
          backgroundColor,
          textColor,
          placeholderColor: isDark ? '#6B7280' : '#9CA3AF',
          accentColor,
          fontFamily,
        });

      }
      onEditorReady?.();
    }, []),
    onFocusChange,
    onHeightChange: useCallback((height: number) => {
      // Add some padding and clamp minimum
      setWebViewHeight(Math.max(300, height + 20));
    }, []),
  });

  // Expose bridge to parent
  useEffect(() => {
    if (bridgeRef) {
      bridgeRef.current = bridge;
    }
  }, [bridge, bridgeRef]);

  // Sync theme changes
  const prevThemeRef = useRef({ backgroundColor, textColor, accentColor, isDark, fontFamily });
  useEffect(() => {
    const prev = prevThemeRef.current;
    if (
      prev.backgroundColor !== backgroundColor ||
      prev.textColor !== textColor ||
      prev.accentColor !== accentColor ||
      prev.isDark !== isDark ||
      prev.fontFamily !== fontFamily
    ) {
      prevThemeRef.current = { backgroundColor, textColor, accentColor, isDark, fontFamily };
      bridge.setTheme({
        backgroundColor,
        textColor,
        placeholderColor: isDark ? '#6B7280' : '#9CA3AF',
        accentColor,
        fontFamily,
      });
    }
  }, [backgroundColor, textColor, accentColor, isDark, fontFamily, bridge]);

  return (
    <View style={[styles.container, { height: webViewHeight }]}>
      <WebView
        ref={bridge.webViewRef as any}
        source={{ html: EDITOR_HTML }}
        onMessage={bridge.onMessage as (event: WebViewMessageEvent) => void}
        style={[styles.webView, { backgroundColor }]}
        scrollEnabled={false}
        originWhitelist={['*']}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        keyboardDisplayRequiresUserAction={false}
        hideKeyboardAccessoryView={true}
        allowsInlineMediaPlayback={true}
        bounces={false}
        overScrollMode="never"
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        // Prevent WebView from stealing scroll on iOS
        {...(Platform.OS === 'ios' ? { scrollEnabled: false } : {})}
        // Android-specific props
        {...(Platform.OS === 'android' ? {
          androidLayerType: 'hardware',
          mixedContentMode: 'always',
        } : {})}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    overflow: 'hidden',
  },
  webView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
});
